// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameCompany = "company"

// Company mapped from table <company>
type Company struct {
	Id          int64     `gorm:"column:id;primaryKey;comment:auto-increment id" json:"id"`          // auto-increment id
	CompanyName string    `gorm:"column:company_name;comment:company name" json:"company_name"` // company name
	CreateTime  time.Time `gorm:"column:create_time;comment:create time" json:"create_time"`   // create time
	UpdateTime  time.Time `gorm:"column:update_time;comment:update time" json:"update_time"`   // update time
}

// TableName Company's table name
func (*Company) TableName() string {
	return TableNameCompany
}
